# Unit 5 Anthropology - Final Project

Exploring the AMNH collections database for mocassins and reporting their color combinations. 

Create at least two functions to find the following using Claire Heckel's moccasin data:
1. How many color combinations are used on moccasins? How many moccasins have a combination of 3 colors?
2. Which color combinations occur most often in our moccasins data (min/max)?
3. What are the three most common pairs of motifs on moccasins? What are the least common?

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

In [ ]:
claire_data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/ClairesMoccasinData - Data.csv")

In [ ]:
color_combos_2 = open("/content/drive/MyDrive/Colab Notebooks/2_color_combos.txt").read()

In [ ]:
color_combos_3 = open("/content/drive/MyDrive/Colab Notebooks/3_color_combos.txt").read()

In [ ]:
motif_combos_3 = open("/content/drive/MyDrive/Colab Notebooks/3_motif_combos.txt").read()

In [ ]:
color_combos_4 = open("/content/drive/MyDrive/Colab Notebooks/4_color_combos.txt").read()

In [ ]:
motif_combos_4 = open("/content/drive/MyDrive/Colab Notebooks/4_motif_combos.txt").read()

In [ ]:
color_combos_5 = open("/content/drive/MyDrive/Colab Notebooks/5_color_combos.txt").read()

In [ ]:
motif_combos_5 = open("/content/drive/MyDrive/Colab Notebooks/5_motif_combos.txt").read()

In [ ]:
claire_data.head()

      CATNO  ACCYEAR  CULTURE  ...  MOTIF_TWISTED  MOTIF_VERTEBRAE  OTHER
0  502.5947        0        1  ...              0                0      0
1  502.5947        0        1  ...              0                0      0
2    50.623     1899        1  ...              0                0      0
3    50.381     1899        1  ...              0                0      0
4    50.643     1899        1  ...              0                0      0

[5 rows x 91 columns]

In [ ]:
#def culture_focus (): 
for i in claire_data.columns:
  if "1" in i:
    claire_data = claire_data.drop([i], axis = 1)

print(claire_data)

        CATNO  ACCYEAR  CULTURE  ...  MOTIF_TWISTED  MOTIF_VERTEBRAE  OTHER
0    502.5947        0        1  ...              0                0      0
1    502.5947        0        1  ...              0                0      0
2      50.623     1899        1  ...              0                0      0
3      50.381     1899        1  ...              0                0      0
4      50.643     1899        1  ...              0                0      0
..        ...      ...      ...  ...            ...              ...    ...
436   50.6008     1905       19  ...              0                0      0
437   50.6069     1905       19  ...              0                0      0
438    50.603     1905       19  ...              0                0      0
439   50.6061     1905       19  ...              0                0      0
440  501.7371     1913       20  ...              0                0      0

[441 rows x 90 columns]

In [ ]:
plains_data = claire_data.loc[claire_data["CULTURE"] == 5]
print(plains_data)

        CATNO  ACCYEAR  CULTURE  ...  MOTIF_TWISTED  MOTIF_VERTEBRAE  OTHER
79   502.4411     1940        5  ...              0                0      0
80   502.4582     1942        5  ...              0                0      0
81    502.393     1936        5  ...              0                0      0
82   502.4608     1942        5  ...              0                0      0
83   502.5343     1947        5  ...              0                0      0
..        ...      ...      ...  ...            ...              ...    ...
184  502.3925     1936        5  ...              0                0      0
185  502.3931     1936        5  ...              0                0      0
186  502.5505     1948        5  ...              0                0      0
187  502.5348     1948        5  ...              0                0      0
188  502.3932     1936        5  ...              0                0      0

[110 rows x 90 columns]

In [ ]:
len(color_combos_2)

11372

In [ ]:
len(color_combos_3)

190926

In [ ]:
len(motif_combos_3)

304249

In [ ]:
len(color_combos_4)

2054007

In [ ]:
len(motif_combos_4)

3262776

In [ ]:
len(color_combos_5)

15999720

In [ ]:
len(motif_combos_5)

25367672

In [ ]:
plains_data = claire_data.loc[claire_data["CULTURE"] == 5]
plains_data.head()

       CATNO  ACCYEAR  CULTURE  ...  MOTIF_TWISTED  MOTIF_VERTEBRAE  OTHER
79  502.4411     1940        5  ...              0                0      0
80  502.4582     1942        5  ...              0                0      0
81   502.393     1936        5  ...              0                0      0
82  502.4608     1942        5  ...              0                0      0
83  502.5343     1947        5  ...              0                0      0

[5 rows x 90 columns]

In [ ]:
plains_data.columns
for i in plains_data.columns: 
  if "LOCALE" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "SIZE" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "CUFFTYPE" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "CUFFSEWN" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "LACES" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "FRINGE" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "HEELTABS" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "DECOLAYOUT" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "BORDERMOTIF" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "BORDERROWS" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "TOEMAKER" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_ANTELOPEHOOF" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_ARROW" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_BIRD" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_BOX" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_BOXPLOT" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_CHECKER" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_CHEVRON" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_CROSSBAR" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_DIAMO9" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_DRAGONFLY" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_ELKHOOF" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_HOURGLASS" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_FEATHER" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_FILLEDUP" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_FULLPOINTS" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_HALFSTAR" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_HEARTLUNGS" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_HORSETRACKS" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_IBAR" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_LEAF" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_LIGHTNING" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_LONGCHECKER" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_MORNINGSTAR" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_MOUNTAIN" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_POINTS" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_RABBITEARS" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_RABBITTRACKS" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_SLANTBAR" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_SQUARECROSS" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_STRIPES" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_TIPI" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_TRIANGLES" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_TURTLE" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_TWISTED" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "MOTIF_VERTEBRAE" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "OTHER" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "CATNO" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "ACCYEAR" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "CULTURE" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "TOEMARKER" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "GENDER" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "BEADED" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "QUILLED" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "TONGUETYPE" in i:
    plains_data = plains_data.drop([i], axis = 1)
  elif "TONGUESEWN" in i:
    plains_data = plains_data.drop([i], axis = 1)
plains_data.head()

    BLACK  ...  Number_of_colors
79      0  ...                29
80      0  ...                26
81      1  ...                20
82      0  ...                39
83      0  ...                31

[5 rows x 37 columns]

In [ ]:
plains_data["color_combo"] = 0
plains_data["Number_of_colors"] = 0
plains_data["color_combo"] = plains_data["color_combo"].astype("object")
plains_data["Number_of_colors"] = plains_data["Number_of_colors"].astype("object")
plains_data.head()

    BLACK  TR_CRYSTAL  WHITE  ...  REDWHITEINT  color_combo  Number_of_colors
79      0           0      0  ...            0            0                 0
80      0           0      1  ...            0            0                 0
81      1           0      0  ...            0            0                 0
82      0           0      1  ...            1            0                 0
83      0           0      0  ...            0            0                 0

[5 rows x 37 columns]

In [ ]:
color_combos = []
def colors(df, row):
  for i in plains_data:
    if row.loc[plains_data[row]] == 1:
      color_combos.append()

colors(plains_data, 79)

AttributeError: ignored

In [ ]:
for index, row in plains_data.iterrows():
  color_combo = []
  for i in plains_data.columns:
    if row.loc[i] == 1:
      plains_data.at[index, "color_combo"] = color_combo
      plains_data.at[index, "Number_of_colors"] = len(color_combo)
    color_combo.append(i)
plains_data

     BLACK  ...  Number_of_colors
79       0  ...                24
80       0  ...                21
81       1  ...                15
82       0  ...                34
83       0  ...                26
..     ...  ...               ...
184      0  ...                28
185      1  ...                34
186      1  ...                26
187      0  ...                33
188      0  ...                34

[110 rows x 37 columns]